const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getPathForFile: (file) => webUtils.getPathForFile(file),
  setIgnoreMouseEvents: (ignore, forward) => ipcRenderer.invoke('set-ignore-mouse-events', ignore, forward),
  controlSystemMedia: (action) => ipcRenderer.invoke('control-system-media', action),
  getSystemMedia: () => ipcRenderer.invoke('get-system-media'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openSettings: () => ipcRenderer.send('open-settings'),
  hideIsland: () => ipcRenderer.send('hide-island'),
  quitApp: () => ipcRenderer.send('quit-app'),
  log: (msg) => ipcRenderer.invoke('log', msg),
  writeFilesToClipboard: (filePaths) => ipcRenderer.invoke('write-files-to-clipboard', filePaths),
  startDrag: (filePath) => ipcRenderer.send('ondragstart', filePath),
  saveChatHistory: (chat) => ipcRenderer.invoke('save-chat-history', chat),
  getChatHistory: () => ipcRenderer.invoke('get-chat-history'),
  deleteChatHistoryItem: (id) => ipcRenderer.invoke('delete-chat-history-item', id),
  clearChatHistory: () => ipcRenderer.invoke('clear-chat-history'),
  onDragFinished: (callback) => ipcRenderer.on('drag-finished', (event, path) => callback(path)),
  getClipboardHistory: () => ipcRenderer.invoke('get-clipboard-history'),
  copyToClipboard: (item) => ipcRenderer.invoke('copy-to-clipboard', item),
  clearClipboardHistory: () => ipcRenderer.invoke('clear-clipboard-history'),
  deleteClipboardItem: (timestamp) => ipcRenderer.invoke('delete-clipboard-item', timestamp),
  onClipboardUpdate: (callback) => ipcRenderer.on('clipboard-update', (event, history) => callback(history)),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  changeVolume: (direction) => ipcRenderer.invoke('change-volume', direction),
  getVolume: () => ipcRenderer.invoke('get-volume'),
  changeBrightness: (direction) => ipcRenderer.invoke('change-brightness', direction),
  getBrightness: () => ipcRenderer.invoke('get-brightness'),
  saveTodo: (todos) => ipcRenderer.invoke('save-todo', todos),
  getTodo: () => ipcRenderer.invoke('get-todo'),
  getCalendarEvents: () => ipcRenderer.invoke('get-calendar-events'),
  saveCalendarEvents: (events) => ipcRenderer.invoke('save-calendar-events', events),
  googleCalendarConnect: () => ipcRenderer.invoke('google-calendar-connect'),
  googleCalendarDisconnect: () => ipcRenderer.invoke('google-calendar-disconnect'),
  googleCalendarSync: () => ipcRenderer.invoke('google-calendar-sync'),
  googleCalendarStatus: () => ipcRenderer.invoke('google-calendar-status'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, status) => callback(status)),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  quitAndInstall: () => ipcRenderer.send('quit-and-install')
});
